print("Witaj Świecie!")
print("Jak masz na imię?")
myName = input()
print("Miło Cię poznać," + myName + ".")
print("Liczba znaków Twoim imieniu wynosi:")
print(len(myName))
print("ile masz lat?")
myAge = input()
print("Za rok będziesz mieć " +str(int(myAge)+1) + "lat.")